# -*- coding: utf-8 -*-
"""MinorProject(DS).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/147Lwf3yGzT5xrfim9XwaXjEFuluFu8Qn

It is a Minor Project to explore data.
* Library used - Pandas
* Dataset used - https://www.kaggle.com/ronitf/heart-disease-uci
* Data Description - All column names are self explanatory

To access the given dataset by using pandas library, I can use the following code:
"""

import pandas as pd
d=pd.read_csv(" https://raw.githubusercontent.com/arora123/Data/master/Automobile_data.csv")
df=pd.DataFrame(d)
print(d)

"""A. Is there any missing values in the data? If yes, drop the rows with missing values.

Code:
"""

missing_values = df.isna().sum()
print("Missing values in each column:")
print(missing_values)

# Drop rows with missing values
df_cleaned = df.dropna()

# Display the cleaned DataFrame
print("\nCleaned DataFrame:")
print(df_cleaned)

"""B. And answer the following question.

1. which are the cars with minimum or maximum price?

Code:
"""

min_price_car = df.loc[df['price'] == df['price'].min()]
max_price_car = df.loc[df['price'] == df['price'].max()]
print("Cars with minimum price:\n", min_price_car)
print("Cars with maximum price:\n", max_price_car)

"""2. How many cars are there with different body-styles?

Code:
"""

body_style_counts = df['body-style'].value_counts()
print("\nNumber of cars with different body-styles:\n", body_style_counts)

"""3. What is the average price of all body types of cars? Arrange them in descending order

Code:
"""

average_price_body_style = df.groupby('body-style')['price'].mean().sort_values(ascending=False)
print("\nAverage price of all body types of cars in descending order:\n", average_price_body_style)

"""4. What is the average price of cars by different companies? Arrange them in descending order"""

average_price_company = df.groupby('company')['price'].mean().sort_values(ascending=False)
print("\nAverage price of cars by different companies in descending order:\n", average_price_company)

"""5. Count car types have diffeent number cylinders?"""

cylinder_counts = df['num-of-cylinders'].value_counts()
print("\nCount of car types with different number of cylinders:\n", cylinder_counts)